apiVersion: v1
kind: Service
metadata:
  name: finassist
  labels:
    app: finassist
spec:
  type: ClusterIP
  selector:
    app: finassist
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
